# docker-compose.yml
version: "3.9"

services:
   database:
      image: postgres:14.2
      env_file:
         - database.env #configuration for postgres
      volumes:
         - database-data:/var/lib/postresql/data/
      ports:
         - "5432:5432"
   mailserver: #Will auto generate new users upon receiving mails
      image: greenmail/standalone:1.6.7
      environment:
         - JAVA_OPTS=-Dgreenmail.verbose
      ports:
         - 3025:3025 # SMTP
         - 3110:3110 # POP3
         - 3143:3143 # IMAP
         - 3465:3465 # SMTPS
         - 3993:3993 # IMAPS
         - 3995:3995 # POP3S
         - 8081:8080 # API
   mailclient: #base user is "username" "password" for credentials
      image: roundcube/roundcubemail:1.5.2-apache
      depends_on:
         - mailserver
      ports:
         - 8000:80
      environment:
         - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver  # IMAP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS
         - ROUNDCUBEMAIL_DEFAULT_PORT=3143       # IMAP port
         - ROUNDCUBEMAIL_SMTP_SERVER=mailserver   # SMTP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS
         - ROUNDCUBEMAIL_SMTP_PORT=3025          # SMTP port


         
volumes:
   database-data:

