# docker-compose.yml
version: '3'

services:
   database:
      image: postgres:14.2
      env_file:
         - database.env #configuration for postgres
      volumes:
         - database-data:/var/lib/postresql/data/
      ports:
         - "5432:5432"
         
volumes:
   database-data:

