# docker-compose-full.yml
# Launch the whole application for local testing.
# the application need to be built beforehand and dockerized with the
# Dockerfile located in the this same folder with the command: docker build -t todolist .
version: "2.4"

services:
   database:
      image: postgres:14.2
      environment:
         - POSTGRES_USER=testUser
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=todoListAppTestDb
      volumes:
         - database-data:/var/lib/postresql/data/
      ports:
         - "5432:5432"
   todolist:
      image: todolist:latest
      depends_on:
         - database
      environment:
         - spring.datasource.url=jdbc:postgresql://database:5432/todoListAppTestDb
         - todolist.verification.email.host=mailserver
      ports:
         - 8080:8080

         
volumes:
   database-data:

