name: Java_CI

on: 
   push:
   pull_request:

jobs:
   build:
      name: Build
      runs-on: ubuntu-latest
      
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
              
         - name: Set up JDK 17
           uses: actions/setup-java@v2
           with:
             java-version: '17'
             distribution: 'adopt'
             
         - name: Cache SonarCloud packages
           uses: actions/cache@v1
           with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar
             
         - name: Cache Maven packages
           uses: actions/cache@v3
           with:
             path: ~/.m2
             key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
             restore-keys: ${{ runner.os }}-m2   
             
         - name: JUnit Report
           uses: actions/upload-artifact@v2
           path: '**/target/site'
           
         - name: Build with Maven (unit and integration tests)
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_TOKEN}} 
           run: >
               mvn --batch-mode --update-snapshots verify
               sonar:sonar -Dsonar.projectKey=Predictabowl_todolist-app
               coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
