name: Java_CI E2E tests

on:
   push:

jobs:
   build:
      name: Build
      runs-on: ubuntu-latest
      
#      services:
#         chrome:
#            image: selenium/standalone-chrome:4.1.2-20220317
#            ports:
#               - "4442:4442"
#               - "4443:4443"
#               - "4444:4444"
               
      steps:
         - uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Set up JDK 17
           uses: actions/setup-java@v2
           with:
             java-version: '17'
             distribution: 'adopt'
         - name: Cache SonarCloud packages
           uses: actions/cache@v1
           with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar
         - name: Cache Maven packages
           uses: actions/cache@v3
           with:
             path: ~/.m2
             key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
             restore-keys: ${{ runner.os }}-m2
         - name: JUnit Report
           uses: actions/upload-artifact@v2
           with:
              name: surefire-report
              path: '**/target/site'
         - name: chrome
           uses: browser-actions/setup-chrome@latest
         - run: chrome --version
         - name: Build with Maven (end to end only)
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: mvn --batch-mode --update-snapshots verify -Pe2e-tests
